#!/usr/bin/env bash
# =============================================================
# AegisPay — iOS Build & Run  (macOS)
#
# Builds the AegisPay iOS app and installs it on the iOS
# Simulator (or a connected physical device with -d).
# Assumes the backend is already running (via start-local.sh
# or Docker + individual services).
#
# Usage:
#   ./start-ios.sh                  — simulator  (localhost)
#   ./start-ios.sh <device-ip>      — physical device on your LAN
#
# Prerequisites:
#   - Xcode 15+ installed  (xcodebuild must be on PATH)
#   - iOS Simulator created in Xcode ▸ Window ▸ Devices & Simulators
#   - xcrun / simctl  (bundled with Xcode)
#   - Optional: STRIPE_PUBLISHABLE_KEY in env for Stripe test mode
# =============================================================

set -euo pipefail

BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
RED="\033[31m"
RESET="\033[0m"

step() { echo -e "${CYAN}${BOLD}▶ $*${RESET}"; }
ok()   { echo -e "${GREEN}✓ $*${RESET}"; }
die()  { echo -e "${RED}✗ $*${RESET}" >&2; exit 1; }

echo ""
echo "========================================================="
echo "  AegisPay — iOS Build & Run  (macOS)"
echo "========================================================="

# =============================================================
# ARGUMENTS
# =============================================================
PHYSICAL_DEVICE=0
DEVICE_IP="localhost"
if [[ "${1:-}" != "" ]]; then
  PHYSICAL_DEVICE=1
  DEVICE_IP="$1"
fi

API_BASE_URL="http://${DEVICE_IP}:8080"
KEYCLOAK_ISSUER="http://${DEVICE_IP}:8180/realms/aegispay"
WS_BASE_URL="ws://${DEVICE_IP}:8090"

# =============================================================
# CREDENTIALS & CONFIG
# =============================================================

# ── Stripe (test mode) ────────────────────────────────────────
STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY:-pk_test_51TTkk2CyjRW67i1Dr44Sfw2W1FzJ2taFP757phrJYxYlwFTThQEEdL2eUnugV6w50ySvXjHUUXO35yHd6y3HAgiP007Aa0VZdL}"

# ── Google OAuth (Keycloak social login) ──────────────────────
# Set GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET in your environment before running.
# Get them from: https://console.cloud.google.com/apis/credentials
[[ -z "${GOOGLE_CLIENT_ID:-}" ]]     && echo "WARNING: GOOGLE_CLIENT_ID not set — Google social login disabled"
[[ -z "${GOOGLE_CLIENT_SECRET:-}" ]] && echo "WARNING: GOOGLE_CLIENT_SECRET not set — Google social login disabled"

# ── Microsoft OAuth (Keycloak social login) ───────────────────
# Set MICROSOFT_CLIENT_ID / MICROSOFT_CLIENT_SECRET in your environment.
# Get them from: https://portal.azure.com/ -> App Registrations -> Certificates and Secrets
[[ -z "${MICROSOFT_CLIENT_ID:-}" ]]     && echo "WARNING: MICROSOFT_CLIENT_ID not set — Microsoft social login disabled"
[[ -z "${MICROSOFT_CLIENT_SECRET:-}" ]] && echo "WARNING: MICROSOFT_CLIENT_SECRET not set — Microsoft social login disabled"
MICROSOFT_TENANT_ID="${MICROSOFT_TENANT_ID:-common}"

# =============================================================
# VERIFY XCODE / XCODEBUILD
# =============================================================
step "Checking Xcode tools..."
if ! command -v xcodebuild &>/dev/null; then
  die "xcodebuild not found. Install Xcode from the Mac App Store."
fi
XCODE_VER=$(xcodebuild -version 2>/dev/null | head -1)
ok "$XCODE_VER"

if ! command -v xcrun &>/dev/null; then
  die "xcrun not found. Install Xcode Command Line Tools: xcode-select --install"
fi

# =============================================================
# WRITE BUILD SETTINGS (xcconfig)
# Injected into the build via -xcconfig flag — avoids modifying
# the Xcode project file and works with SPM-based projects.
# =============================================================
XCCONFIG_PATH="apps/ios/LocalDev.xcconfig"
step "Writing build settings to $XCCONFIG_PATH..."

mkdir -p "$(dirname "$XCCONFIG_PATH")"
cat > "$XCCONFIG_PATH" <<EOF
// LocalDev.xcconfig — auto-generated by start-ios.sh — do NOT commit
API_BASE_URL = ${API_BASE_URL}
WS_BASE_URL = ${WS_BASE_URL}
KEYCLOAK_ISSUER = ${KEYCLOAK_ISSUER}
STRIPE_PUBLISHABLE_KEY = ${STRIPE_PUBLISHABLE_KEY}
GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
MICROSOFT_CLIENT_ID = ${MICROSOFT_CLIENT_ID}
EOF

ok "xcconfig written"

# =============================================================
# PHYSICAL DEVICE OR SIMULATOR
# =============================================================
if [[ "$PHYSICAL_DEVICE" == "1" ]]; then
  echo ""
  echo "Physical device mode — API URLs pointing to ${DEVICE_IP}"
  echo "Connect your device via USB, trust this Mac, then press Enter."
  read -r -p ""

  DEST_ARG="-destination 'generic/platform=iOS'"
  BUILD_ACTION="build"

  step "Building for physical device (Release-like debug)..."
  (
    cd apps/ios
    xcodebuild \
      -scheme AegisPay \
      -configuration Debug \
      -xcconfig "LocalDev.xcconfig" \
      -destination "generic/platform=iOS" \
      -derivedDataPath ".build/DerivedData" \
      API_BASE_URL="${API_BASE_URL}" \
      WS_BASE_URL="${WS_BASE_URL}" \
      KEYCLOAK_ISSUER="${KEYCLOAK_ISSUER}" \
      STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY}" \
      GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
      MICROSOFT_CLIENT_ID="${MICROSOFT_CLIENT_ID}" \
      build
  )
  ok "Build complete — install via Xcode ▸ Window ▸ Devices & Simulators or use ios-deploy"
  exit 0
fi

# =============================================================
# SIMULATOR: FIND OR BOOT
# =============================================================
step "Finding iOS Simulator..."

# Pick the best available simulator: prefer iPhone 16 Pro, then iPhone 15 Pro, then any iPhone
SIM_UDID=$(xcrun simctl list devices available -j 2>/dev/null \
  | python3 -c "
import sys, json
data = json.load(sys.stdin)
order = ['iPhone 16 Pro', 'iPhone 16', 'iPhone 15 Pro', 'iPhone 15', 'iPhone 14 Pro', 'iPhone 14']
devices = []
for runtime, devs in data.get('devices', {}).items():
    if 'iOS' not in runtime:
        continue
    for d in devs:
        if d.get('isAvailable') and 'iPhone' in d.get('name',''):
            devices.append(d)
for name in order:
    for d in devices:
        if d['name'] == name:
            print(d['udid'])
            sys.exit(0)
if devices:
    print(devices[0]['udid'])
" 2>/dev/null || true)

if [[ -z "$SIM_UDID" ]]; then
  # Fall back to env var or first available
  if [[ -n "${IOS_SIMULATOR_UDID:-}" ]]; then
    SIM_UDID="$IOS_SIMULATOR_UDID"
  else
    die "No available iOS Simulator found. Create one in Xcode ▸ Window ▸ Devices & Simulators.
Set IOS_SIMULATOR_UDID=<udid> to specify one explicitly."
  fi
fi

SIM_NAME=$(xcrun simctl list devices -j 2>/dev/null \
  | python3 -c "
import sys, json
data = json.load(sys.stdin)
udid = '$SIM_UDID'
for devs in data.get('devices', {}).values():
    for d in devs:
        if d['udid'] == udid:
            print(d.get('name','Unknown'))
            sys.exit(0)
" 2>/dev/null || echo "Unknown")

ok "Using simulator: ${SIM_NAME}  (${SIM_UDID})"

# Boot if not running
SIM_STATE=$(xcrun simctl list devices -j 2>/dev/null \
  | python3 -c "
import sys, json
data = json.load(sys.stdin)
udid = '$SIM_UDID'
for devs in data.get('devices', {}).values():
    for d in devs:
        if d['udid'] == udid:
            print(d.get('state','Shutdown'))
            sys.exit(0)
" 2>/dev/null || echo "Shutdown")

if [[ "$SIM_STATE" != "Booted" ]]; then
  step "Booting simulator '${SIM_NAME}'..."
  xcrun simctl boot "$SIM_UDID"
fi

# Open Simulator.app so the window appears
open -a Simulator --args -CurrentDeviceUDID "$SIM_UDID" &>/dev/null || true

# Wait for booted state
printf "  Waiting for simulator to be ready..."
for i in $(seq 1 30); do
  STATE=$(xcrun simctl list devices -j 2>/dev/null \
    | python3 -c "
import sys, json
data = json.load(sys.stdin)
for devs in data.get('devices', {}).values():
    for d in devs:
        if d['udid'] == '$SIM_UDID':
            print(d.get('state','Shutdown'))
            sys.exit(0)
" 2>/dev/null || echo "Shutdown")
  if [[ "$STATE" == "Booted" ]]; then
    echo ""
    ok "Simulator ready"
    break
  fi
  printf "."; sleep 2
done

# =============================================================
# BUILD & INSTALL  (SPM / xcodebuild)
# =============================================================
step "Building AegisPay (Debug, Simulator)..."
echo "  API URL   : ${API_BASE_URL}"
echo "  Keycloak  : ${KEYCLOAK_ISSUER}"
echo "  WS        : ${WS_BASE_URL}"
echo "  Google    : ${GOOGLE_CLIENT_ID}"
echo "  Microsoft : ${MICROSOFT_CLIENT_ID}"
echo ""

(
  cd apps/ios
  xcodebuild \
    -scheme AegisPay \
    -configuration Debug \
    -xcconfig "LocalDev.xcconfig" \
    -destination "id=${SIM_UDID}" \
    -derivedDataPath ".build/DerivedData" \
    API_BASE_URL="${API_BASE_URL}" \
    WS_BASE_URL="${WS_BASE_URL}" \
    KEYCLOAK_ISSUER="${KEYCLOAK_ISSUER}" \
    STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY}" \
    GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
    MICROSOFT_CLIENT_ID="${MICROSOFT_CLIENT_ID}" \
    build
)

ok "Build succeeded"

# =============================================================
# INSTALL APP ON SIMULATOR
# =============================================================
step "Installing app on simulator..."

APP_PATH=$(find apps/ios/.build/DerivedData -name "AegisPay.app" -path "*/Debug-iphonesimulator/*" 2>/dev/null | head -1)
if [[ -z "$APP_PATH" ]]; then
  die "Could not find AegisPay.app in DerivedData. Check build output above."
fi

xcrun simctl install "$SIM_UDID" "$APP_PATH"
ok "App installed"

# =============================================================
# LAUNCH APP
# =============================================================
step "Launching AegisPay on simulator..."
xcrun simctl launch "$SIM_UDID" io.aegispay.app
ok "AegisPay iOS launched"

# =============================================================
# SUMMARY
# =============================================================
echo ""
echo "========================================================="
echo "  iOS running!"
echo "========================================================="
echo ""
if [[ "$PHYSICAL_DEVICE" == "1" ]]; then
  echo "  Mode      : Physical device  (${DEVICE_IP})"
else
  echo "  Mode      : Simulator  (${SIM_NAME})"
fi
echo "  API URL   : ${API_BASE_URL}"
echo "  Keycloak  : ${KEYCLOAK_ISSUER}"
echo ""
echo "  Social login (via Keycloak):"
echo "    Google    — uses ${GOOGLE_CLIENT_ID}"
echo "    Microsoft — uses ${MICROSOFT_CLIENT_ID}"
echo ""
echo "  Useful commands:"
echo "    Logs     : xcrun simctl spawn ${SIM_UDID} log stream --predicate 'subsystem == \"io.aegispay.app\"'"
echo "    Reset    : xcrun simctl uninstall ${SIM_UDID} io.aegispay.app"
echo "    Shutdown : xcrun simctl shutdown ${SIM_UDID}"
echo ""
