{{- if .Values.services.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aegispay.labels" . | nindent 4 }}
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "aegispay.selectorLabels" (dict "name" "web" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
{{- end }}
