{{- if .Values.services.transaction_service.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aegispay.labels" . | nindent 4 }}
    app.kubernetes.io/name: transaction-service
data:
  DB_HOST: {{ .Values.global.postgresql.host | quote }}
  DB_PORT: {{ .Values.global.postgresql.port | quote }}
  DB_USERNAME: {{ .Values.global.postgresql.username | quote }}
  DB_NAME: "aegispay_transactions"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.brokers | quote }}
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  MONGODB_URI: {{ .Values.global.mongodb.uri | quote }}
  OAUTH2_ISSUER_URI: {{ .Values.global.oauth2.issuerUri | quote }}
  SERVER_PORT: "8082"
{{- end }}
