{{- if .Values.services.transaction_service.enabled }}
{{ include "aegispay.serviceDeployment" (dict "name" "transaction-service" "key" "transaction_service" "svc" .Values.services.transaction_service "context" .) }}
{{- end }}
