{{- if .Values.services.transaction_service.enabled }}
{{ include "aegispay.serviceNetworkPolicy" (dict "name" "transaction-service" "svc" .Values.services.transaction_service "context" .) }}
{{- end }}
