{{- if .Values.services.ledger_service.enabled }}
{{ include "aegispay.serviceDeployment" (dict "name" "ledger-service" "key" "ledger_service" "svc" .Values.services.ledger_service "context" .) }}
{{- end }}
