{{- if .Values.services.notification_service.enabled }}
{{ include "aegispay.serviceNetworkPolicy" (dict "name" "notification-service" "svc" .Values.services.notification_service "context" .) }}
{{- end }}
