{{- if .Values.services.api_gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aegispay.labels" . | nindent 4 }}
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: api-gateway
spec:
  type: ClusterIP
  selector:
    {{- include "aegispay.selectorLabels" (dict "name" "api-gateway" "context" .) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
