{{- if .Values.services.risk_engine.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-engine-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aegispay.labels" . | nindent 4 }}
    app.kubernetes.io/name: risk-engine
data:
  DB_HOST: {{ include "aegispay.pgHost" . | quote }}
  DB_PORT: {{ .Values.global.postgresql.port | quote }}
  DB_USERNAME: {{ .Values.global.postgresql.username | quote }}
  DB_NAME: "aegispay_risk"
  KAFKA_BOOTSTRAP_SERVERS: {{ include "aegispay.kafkaBroker" . | quote }}
  REDIS_HOST: {{ include "aegispay.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  MONGODB_URI: {{ include "aegispay.mongoUri" . | quote }}
  OAUTH2_JWK_SET_URI: {{ include "aegispay.jwkSetUri" . | quote }}
  SERVER_PORT: "8085"
{{- end }}
