{{- if and .Values.grafana.enabled .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aegispay.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
  {{- with .Values.grafana.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.grafana.ingress.className }}
  ingressClassName: {{ .Values.grafana.ingress.className }}
  {{- end }}
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.grafana.ingress.host | quote }}
      secretName: {{ .Values.grafana.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.grafana.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
{{- end }}
