{{- if .Values.kafkaUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: kafka-ui
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end }}
