{{- if .Values.services.reconciliation_service.enabled }}
{{ include "aegispay.serviceNetworkPolicy" (dict "name" "reconciliation-service" "svc" .Values.services.reconciliation_service "context" .) }}
{{- end }}
