apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegispay-dev
  namespace: argocd
  labels:
    environment: dev
    app.kubernetes.io/part-of: aegispay
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aegispay

  source:
    repoURL: https://github.com/shreyasshelar/AegisPay.git
    targetRevision: main
    path: infra/helm/aegispay
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: aegispay-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas   # allow HPA to override
